# Site settings
title: Ilia's blog
email: barahilia@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  My private corner for sharing thoughts about programming,
  computers and everything.
baseurl: "/blog" # the subpath of your site, e.g. /blog/
url: "http://barahilia.github.io/blog/" # the base hostname & protocol for your site
github_username:  barahilia

# Build settings
markdown: kramdown
