# Site settings
title: Ilia's blog
email: barahilia@gmail.com
description: >
  My private corner for sharing thoughts about programming,
  computers and everything.
baseurl: "/blog"
url: "http://barahilia.github.io/blog/"
github_username:  barahilia

# Build settings
markdown: kramdown
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge
  hard_wrap: false
